Traceback (most recent call last):
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/hernando/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/hernando/opt/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
m_p = units.value("proton mass energy equivalent in MeV")
m_n = units.value("neutron mass energy equivalent in MeV")
m_e = units.value("electron mass energy equivalent in MeV") 
E = ((m_n + m_e)**2 - m_p**2)/(2 * m_p)
print("Energ√≠a umbral del nuetrino = {:4.3f} MeV".format(E))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/56/_pmdccc97ljb_l3v3s6gkrxm0000gn/T/ipykernel_31485/1369934174.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mm_p[0m [0;34m=[0m [0munits[0m[0;34m.[0m[0mvalue[0m[0;34m([0m[0;34m"proton mass energy equivalent in MeV"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mm_n[0m [0;34m=[0m [0munits[0m[0;34m.[0m[0mvalue[0m[0;34m([0m[0;34m"neutron mass energy equivalent in MeV"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0mm_e[0m [0;34m=[0m [0munits[0m[0;34m.[0m[0mvalue[0m[0;34m([0m[0;34m"electron mass energy equivalent in MeV"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mE[0m [0;34m=[0m [0;34m([0m[0;34m([0m[0mm_n[0m [0;34m+[0m [0mm_e[0m[0;34m)[0m[0;34m**[0m[0;36m2[0m [0;34m-[0m [0mm_p[0m[0;34m**[0m[0;36m2[0m[0;34m)[0m[0;34m/[0m[0;34m([0m[0;36m2[0m [0;34m*[0m [0mm_p[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mprint[0m[0;34m([0m[0;34m"Energ√≠a umbral del nuetrino = {:4.3f} MeV"[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mE[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'units' is not defined
NameError: name 'units' is not defined

